/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 scene.gltf
Author: ஜCIHIRISஜ (https://sketchfab.com/crazy4creativity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-toy-dinosaur-d672bf6260d54f4e83ac2d9fa99b9194
Title: Green Toy Dinosaur
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[9.56, 33.128, -64.363]} rotation={[-3.122, 0.163, 0.01]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Stereo_textured_mesh_Material0_0.geometry} material={materials.Material0} />
          <mesh geometry={nodes.Stereo_textured_mesh_Material0_0_1.geometry} material={materials.Material0} />
          <mesh geometry={nodes.Stereo_textured_mesh_Material0_0_2.geometry} material={materials.Material0} />
          <mesh geometry={nodes.Stereo_textured_mesh_Material0_0_3.geometry} material={materials.Material0} />
          <mesh geometry={nodes.Stereo_textured_mesh_Material0_0_4.geometry} material={materials.Material0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
